export const arts = [
  {
    _id: `1`,
    image: `/assets/one.jpg`,
    title: `NO ONE IS HERE, EXCEPT YOU  (II)`,
    medium: `MIXED MEDIA ON CANVAS`,
    dimemsion: `153 CM BY 87 CM (APPROX)`,
    year: 2020,
  },
  {
    _id: `2`,
    image: `/assets/two.jpg`,
    title: `SONG BIRD AND THE TWIN DRUMMER`,
    medium: `NATURAL PIGMENT ON CANVAS`,
    dimemsion: `157 BY 85 (APPROX)`,
    year: 2020,
  },
  {
    _id: `3`,
    image: `/assets/three.jpg`,
    title: `WHERE  WATER DIVIDED THE LAND`,
    medium: `NATURAL PIGMENT ON CANVAS`,
    dimemsion: `84 CM BY 156 CM (APPROX)`,
    year: 2020,
  },
  {
    _id: `4`,
    image: `/assets/four.jpg`,
    title: `PRISONER OF CONSCIENCE`,
    medium: `NATURAL PIGMENT ON PAPER`,
    dimemsion: `48 CM BY 33 CM (APROX)`,
    year: 2014,
  },
  {
    _id: `5`,
    image: `/assets/five.jpg`,
    title: `DON'T WE WON IT  (II)`,
    medium: `MIXED MEDIA ON CANVAS`,
    dimemsion: `155 CM BY 84 CM`,
    year: 2020,
  },
  {
    _id: `6`,
    image: `/assets/six.jpg`,
    title: `ELAROWA  (II)`,
    medium: `NATURAL PIGMENT ON CANVAS`,
    dimemsion: `155 CM BY 84 CM`,
    year: 2020,
  },
  {
    _id: `7`,
    image: `/assets/seven.jpg`,
    title: `BABAILUBATA`,
    medium: `MIXED MEDIA ON CANVAS`,
    dimemsion: `155 BY 84`,
    year: 2020,
  },
  {
    _id: `8`,
    image: `/assets/eight.jpg`,
    title: `WHERE  WATER DIVIDED THE LAND`,
    medium: `MIXED MEDIA ON CANVAS`,
    dimemsion: `84 CM BY 156 CM (APPROX)`,
    year: 2020,
  },
  {
    _id: `9`,
    image: `/assets/nine.jpg`,
    title: `I SLEPT WITH MY SHOES-ON`,
    medium: `NATURAL PIGMENT ON CANVAS`,
    dimemsion: `157 CM BY 85 CM (APROX)`,
    year: 2020,
  },
];
